component/Details.md
samples/android/AndroidSample.sln
samples/android/Properties/AssemblyInfo.cs
samples/android/Sample.csproj
samples/ios-unified/Sample.csproj
samples/ios-unified/iOSSample.sln
src/AirshipBindings.Android/AirshipBindings.Android.csproj
src/AirshipBindings.Android/Properties/AssemblyInfo.cs
src/AirshipBindings.iOS/AirshipBindings.iOS.csproj
src/AirshipBindings.iOS/ApiDefinition.cs
src/AirshipBindings.iOS/Properties/AssemblyInfo.cs
src/AirshipBindings.iOS/StructsAndEnums.cs

Got it running on the device long enough to make sure the region event stuff works.
@rlepinski once this is merged I'll build and submit the component and transfer you the creds before monday.

[MB-1747] iOS UARegionEvent bindings

---

.gitignore
UrbanAirship.nuspec
build.sh
component/component.yaml
samples/android/Resources/Resource.designer.cs

Defines a nuspec for a NuGet package. Makes our component a "shell" component that just references the NuGet package. Added a build.sh file to automate building everything.
Tested the package and it seems to work.

[MB-1757] First attempt at NuGet packaging

---

UrbanAirship.nuspec
component/Details.md
component/component.yaml
samples/android/AndroidSample.sln
samples/android/Properties/AssemblyInfo.cs
samples/android/Sample.csproj
samples/ios-unified/Sample.csproj
samples/ios-unified/iOSSample.sln
src/AirshipBindings.Android/AirshipBindings.Android.csproj
src/AirshipBindings.Android/Properties/AssemblyInfo.cs
src/AirshipBindings.iOS/AirshipBindings.iOS.csproj
src/AirshipBindings.iOS/ApiDefinition.cs
src/AirshipBindings.iOS/Properties/AssemblyInfo.cs

https://support.urbanairship.com/entries/109237723

MB-1857 - Xamarin 2.2.1 Update

---

samples/android/AndroidSample.sln
samples/android/Sample.csproj
samples/ios-unified/Sample.csproj
samples/ios-unified/iOSSample.sln
src/AirshipBindings.Android/AirshipBindings.Android.csproj
src/AirshipBindings.Android/AirshipBindings.Android.sln
src/AirshipBindings.Android/Properties/AssemblyInfo.cs
src/AirshipBindings.iOS/AirshipBindings.iOS.csproj
src/AirshipBindings.iOS/AirshipBindings.iOS.sln
src/AirshipBindings.iOS/Properties/AssemblyInfo.cs
src/SharedAssemblyInfo.cs
update_version.sh

Changes:
- Remove extra versioning from sln and csproj files
- Added a SharedAssemblyInfo.cs
- Added script to update the version (nuget, yaml, SharedAssemblyInfo)

Versioning

---

AirshipAppExtensions.nuspec
UrbanAirship.Portable.nuspec
UrbanAirship.nuspec
airship.properties
component/Details.md
component/component.yaml
src/SharedAssemblyInfo.cs

Release version 4.1.1

---

samples/ios-unified/AppDelegate.cs
samples/ios-unified/Sample.csproj
src/AirshipBindings.iOS/ApiDefinition.cs

- Updated the bindings with proper memory assignment.
- Fixed the registration delegate implementation.

[MB-2138] Updated bindings and fixed registration delegate imp

---

build.gradle

Remove components during clean

Remove components during clean

---

.gitignore
gradle/wrapper/gradle-wrapper.properties
src/AirshipBindings.iOS/build.gradle

Should address https://github.com/urbanairship/ios-library/issues/128

Strip debug symbols during iOS build

---

AirshipAppExtensions.nuspec
UrbanAirship.Portable.nuspec
UrbanAirship.nuspec
airship.properties
component/Details.md
component/component.yaml
src/SharedAssemblyInfo.cs

Release 4.2.2

---

src/AirshipBindings.Android/Additions/ActionCompletionCallback.cs
src/AirshipBindings.Android/Additions/ActionRegistry.cs
src/AirshipBindings.Android/Additions/ActionRunRequest.cs
src/AirshipBindings.Android/Additions/MessageListFragment.cs
src/AirshipBindings.Android/Additions/PreferenceDataStore.cs
src/AirshipBindings.Android/Additions/RichPushInbox.cs
src/AirshipBindings.Android/Additions/RichPushUser.cs
src/AirshipBindings.Android/Additions/UALocationManager.cs
src/AirshipBindings.Android/Additions/UAWebViewClient.cs
src/AirshipBindings.Android/AirshipBindings.Android.csproj

[MB-2133] Adds delegate methods

[MB-2133] Adds delegate methods

---

src/AirshipBindings.Android/AirshipBindings.Android.csproj
src/AirshipBindings.Android/packages.config

Update support/gps libraries

---

src/AirshipBindings.Android/Additions/AirshipGcmTaskService.cs
src/AirshipBindings.Android/Additions/ChannelCaptureActivity.cs
src/AirshipBindings.Android/AirshipBindings.Android.csproj
src/AirshipBindings.Android/Transforms/Metadata.xml

Fix missing manifest items

---

AirshipAppExtensions.nuspec
Cartfile
UrbanAirship.Portable.nuspec
UrbanAirship.nuspec
airship.properties
component/Details.md
component/component.yaml
src/SharedAssemblyInfo.cs

Release 4.4.1

---

AirshipAppExtensions.nuspec
CHANGELOG.md
UrbanAirship.Portable.nuspec
UrbanAirship.nuspec
airship.properties
component/component.yaml
src/AirshipBindings.iOS/ApiDefinition.cs
src/SharedAssemblyInfo.cs

Enable use of IUAInAppMessageControllerDelegate protocol.

Release 4.6.3

---

UrbanAirship.Android.ADM.nuspec
UrbanAirship.Android.Core.nuspec
UrbanAirship.Android.FCM.nuspec
UrbanAirship.Android.GCM.nuspec
UrbanAirship.NETStandard.nuspec
UrbanAirship.Portable.nuspec
UrbanAirship.iOS.AppExtensions.nuspec
UrbanAirship.iOS.nuspec
build.gradle

This PR moves publishing logic from CI into the repo.

[MOBILE-185] Add nuget publishing to build.gradle

---

CHANGELOG.md
Cartfile
UrbanAirship.NETStandard.nuspec
UrbanAirship.Portable.nuspec
UrbanAirship.iOS.AppExtensions.nuspec
UrbanAirship.iOS.nuspec
airship.properties
samples/ios-unified/InboxDelegate.cs
samples/ios-unified/MessageCenterViewController.cs
src/AirshipBindings.iOS/ApiDefinition.cs
src/AirshipBindings.iOS/StructsAndEnums.cs
src/SharedAssemblyInfo.cs

Updates the iOS xamarin component to SDK 10.0.1
People want to use the new bits.
Ran the sample.

[MOBILE-337] Update to UA iOS SDK 10

---

samples/android/SampleAutopilot.cs
samples/android/UrbanAirshipListener.cs

Fix the message center action (^mc) in the Xamarin Android sample app.
Keep stuff working.
Build and manual test.
https://urbanairship.slack.com/files/U3M8XNZ0T/FKS8X8QP8/message-center-action.webm

[MOBILE-700] Fix message center action.

---

samples/ios-unified/PushSettingsViewController.cs

Fix some problems with the display and control of push settings in the sample Settings view I found during testing.
Want to keep the sample apps working correctly.
Build & run on device.
This screenshot shows the authorizations displaying in the `Push Enabled` cell:

Xamarin: Fix push settings view

---

.github/workflows/ci.yaml

[MOBILE-1386] CI

---

CHANGELOG.md
Cartfile
UrbanAirship.NETStandard.nuspec
UrbanAirship.Portable.nuspec
UrbanAirship.iOS.Accengage.nuspec
UrbanAirship.iOS.Automation.nuspec
UrbanAirship.iOS.Core.nuspec
UrbanAirship.iOS.ExtendedActions.nuspec
UrbanAirship.iOS.Location.nuspec
UrbanAirship.iOS.MessageCenter.nuspec
UrbanAirship.iOS.NotificationContentExtension.nuspec
UrbanAirship.iOS.NotificationServiceExtension.nuspec
UrbanAirship.iOS.nuspec
airship.properties
src/SharedAssemblyInfo.iOS.cs

Release 12.0.1

---

SampleApp/SampleApp.Android/SampleApp.Android.csproj
SampleApp/SampleApp.Android/SampleAutopilot.cs
SampleApp/SampleApp.Android/build.gradle
SampleApp/SampleApp.iOS/SampleApp.iOS.csproj
SampleApp/SampleApp.iOS/build.gradle
SampleApp/SampleApp/SampleApp.csproj
SampleApp/build.gradle
SampleApp/nuget.config
src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/Attributes/AttributeEditor.cs
src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/Airship.cs
src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs
src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.sln
src/AirshipBindings.iOS.Core/ApiDefinitions.cs

This adds date attribute support to our NETStandard library. I tested it manually on iOS and Android with the new sample, which required a fair amount of work to get it to build. I'll call out those changes in the diff.

[MOBILE-1562] date attribute support

---

documentation/migration-guide-fcm.md

Change instances of "master" to "main" after master branch was renamed to main.
Doc links would be broken.
Verified link.

[MOBILE-1736] Change instances of "master" to "main".

---

Airship.NETStandard.nuspec
Airship.iOS.Accengage.nuspec
Airship.iOS.Automation.nuspec
Airship.iOS.Basement.nuspec
Airship.iOS.Chat.nuspec
Airship.iOS.Core.nuspec
Airship.iOS.ExtendedActions.nuspec
Airship.iOS.Location.nuspec
Airship.iOS.MessageCenter.nuspec
Airship.iOS.NotificationContentExtension.nuspec
Airship.iOS.NotificationServiceExtension.nuspec
Airship.iOS.PreferenceCenter.nuspec
Airship.iOS.nuspec
Cartfile
SampleApp/SampleApp.iOS/SampleApp.iOS.csproj
SampleApp/SampleApp/SampleApp.csproj
airship.properties
src/AirshipBindings.iOS.Automation/ApiDefinitions.cs
src/SharedAssemblyInfo.Common.cs
src/SharedAssemblyInfo.CrossPlatform.cs
src/SharedAssemblyInfo.iOS.cs

Update to latest iOS sdk 16.5.1
Run sample app

Update to latest iOS SDK 16.5.1

---

CHANGELOG.md

Prepare release xamarin 16.0.1

Prepare xamarin release 16.0.1
