UrbanAirship.nuspec, component/Details.md, component/component.yaml, samples/android/Sample.csproj, samples/ios-unified/Sample.csproj, src/AirshipBindings.Android/AirshipBindings.Android.csproj, src/AirshipBindings.Android/AirshipBindings.Android.sln, src/AirshipBindings.Android/Properties/AssemblyInfo.cs, src/AirshipBindings.Android/packages.config, src/AirshipBindings.iOS/AirshipBindings.iOS.csproj, src/AirshipBindings.iOS/Properties/AssemblyInfo.cs
I believe this fixes missing bindings for most of the packages in UrbanAirship.Push.Notifications.
=> Fix missing support-v4 bindings

src/AirshipBindings.iOS/ApiDefinition.cs
Fixes #31 
The constant is listed here - https://github.com/urbanairship/ios-library/blob/master/Airship/Common/UALocationEvent.h#L47 but is never actually defined nor used in the SDK.
=> Remove unused/undefined extern constant

AirshipAppExtensions.nuspec, UrbanAirship.nuspec, component/Details.md, component/component.yaml, src/AirshipBindings.iOS/AirshipBindings.iOS.csproj, src/AirshipExtensionBindings.iOS/AirshipExtensionBindings.iOS/AirshipExtensionBindings.iOS.csproj, src/AirshipExtensionBindings.iOS/AirshipExtensionBindings.iOS/AirshipExtensionsApiDefinition.cs, src/AirshipExtensionBindings.iOS/AirshipExtensionBindings.iOS/AirshipExtensionsStructs.cs, src/AirshipExtensionBindings.iOS/AirshipExtensionBindings.iOS/Structs.cs, src/SharedAssemblyInfo.cs, update_version.sh
Fixes the extension for reals this time. 
The main airship bindings needs to contain the AirshipExtensions framework so its actually available in the app bundle. Extensions dependencies are ignored (Xamarin limitation). However we cant have the extension reference the main framework, for whatever reasons that fails. So we have the main package that includes both frameworks and an extension only framework for the extension. Yay.
=> Fix iOS notification service extension

UrbanAirship.Portable.nuspec
Currently when attempting to install the urbanairship.portable package into a PCL in a Xamarin Forms project the install will fail because it depends on urbanairship which has no assembly to match that profile.
Updated the nuspec file so only platform specific version of urbanairship.portable have that dependency.
=> Resolve Issue with urbanairship.portable install into PCL

AirshipAppExtensions.nuspec, CHANGELOG.md, UrbanAirship.Portable.nuspec, UrbanAirship.nuspec, airship.properties, build.gradle, component/component.yaml, samples/ios-unified/PushHandler.cs, src/AirshipBindings.iOS/ApiDefinition.cs, src/SharedAssemblyInfo.cs
Fix deep link action and sample push handler issues
- ActionBlock had incorrect binding, causing a run-time exception.
- Sample Push Handler was not validating a pointer, causing an NPE.
Fix build.gradle to update version that was being missed.
Manually tested on iOS 11.
=> Release 4.6.1

samples/android/Sample.csproj, samples/android/packages.config, samples/ios-unified/Sample.csproj
There were two issues:
- "Firstly, with the release of iOS 11 the simulator, as well as real devices, will not launch 32bit only applications. In your iOS sample it is set to target only i386 instead of i386 – x86_64."
- Fixed by adding x86_64 to the release build.
- "Secondly, the android sample has a missing dependency on CardView which means it won’t compile. Adding the nuget allows it to compile and run successfully."
- Fixed by adding CardView to list of packages. A bunch of other packages updated automagically.
Note: all of the changes are to the sample code, so I will not be re-releasing the SDK. I will, however, advance the 4.6.1 tag in GitHub.
=> Fix Xamarin Store submission issues.

samples/ios-unified/Info.plist, samples/ios-unified/Sample.csproj, samples/ios-unified/SampleServiceExtension/Entitlements.plist, samples/ios-unified/SampleServiceExtension/Info.plist, samples/ios-unified/SampleServiceExtension/NotificationService.cs, samples/ios-unified/SampleServiceExtension/SampleServiceExtension.csproj, samples/ios-unified/SampleServiceExtension/packages.config, samples/ios-unified/iOSSample.sln
Had to figure out to do this to answer a customer question about it. Might as well just put it in the repo. I also changed the bundle id to the same as our iOS samples, so I won't keep forgetting to change it when I'm testing.
=> Add UA notification service extension to sample app

AirshipAppExtensions.nuspec, CHANGELOG.md, UrbanAirship.Portable.nuspec, UrbanAirship.nuspec, airship.properties, component/component.yaml, src/AirshipBindings.iOS/ApiDefinition.cs, src/SharedAssemblyInfo.cs
Changes the type of UAInbox delegates to the "IUAInboxDelegate" protocol, so classes that implement that protocol can be UAInboxDelegates. Doesn't require any source changes.
=> Enable use of IUAInboxDelegate protocol

AirshipAppExtensions.nuspec, CHANGELOG.md, UrbanAirship.Portable.nuspec, UrbanAirship.nuspec, airship.properties, component/component.yaml, src/AirshipBindings.iOS/ApiDefinition.cs, src/SharedAssemblyInfo.cs
- Enable use of UAMessageCenterMessageViewController class.
- Enable use of initWithNibName:bundle: method in UAMessageCenterMessageViewController and UADefaultMessageCenterMessageViewController classes.
=> Release 4.6.4

.gitignore, UrbanAirship.Android.FCM.nuspec, build.gradle, samples/android/packages.config, src/AirshipBindings.Android.Core/AirshipBindings.Android.Core.csproj, src/AirshipBindings.Android.Core/packages.config, src/AirshipBindings.Android.FCM/AirshipBindings.Android.FCM.csproj, src/AirshipBindings.Android.FCM/packages.config
- Add `Xamarin.GooglePlayServices.Base` as a dependency of the `UrbanAirship.Android.FCM` package, so it doesn't need to be manually added to Xamarin apps. `Xamarin.GooglePlayServices.Base` is already in UrbanAirship.Android.FCM` as a dependency of `Xamarin.GooglePlayServices.Gcm`
- Fix deletion of local nuget feed
- Remove xamarin component build (The Component Store has been discontinued as of May 15, 2018.)
Tested on sample app with FCM and GCM.
=> [MOBILE-178] Some dependency cleanup

CHANGELOG.md, Cartfile, UrbanAirship.Android.ADM.nuspec, UrbanAirship.Android.Core.nuspec, UrbanAirship.Android.FCM.nuspec, UrbanAirship.Android.GCM.nuspec, UrbanAirship.NETStandard.nuspec, UrbanAirship.Portable.nuspec, UrbanAirship.iOS.AppExtensions.nuspec, UrbanAirship.iOS.nuspec, airship.properties, samples/ios-unified/SampleServiceExtension/SampleServiceExtension.csproj, samples/ios-unified/SampleServiceExtension/packages.config, samples/ios-unified/iOSSample.sln, src/AirshipBindings.Android.ADM/AirshipBindings.Android.ADM.csproj, src/AirshipBindings.Android.Core/AirshipBindings.Android.Core.csproj, src/AirshipBindings.Android.FCM/AirshipBindings.Android.FCM.csproj, src/AirshipBindings.Android.GCM/AirshipBindings.Android.GCM.csproj, src/AirshipBindings.iOS/ApiDefinition.cs, src/AirshipBindings.iOS/StructsAndEnums.cs, src/SharedAssemblyInfo.cs
Updates the Xamarin bindings to the latest SDK versions
Built the stuff, verified there were no errors or glaring issues. Ran the samples.
This is the second bindings release to use Xamboni, so take a closer look at the ApiDefinition.cs and StructsAndEnums.cs files to makes sure there's nothing crazy going on. It looks fine to my eye, though.
I also made a minor change in the sample app solution structure – the iOS SampleServiceExtension had an out of date dependency on the old app extensions package that caused it to fail to build. This likely slipped through when we were updating our versioning strategy. Instead of building against a package (local or remote) we should just include the app extensions project in the solution and build against a reference to its product, which is what the …
=> MOBILE-243 Update to iOS SDK 9.3.2, Android SDK 9.4 

CHANGELOG.md, Cartfile, UrbanAirship.Android.ADM.nuspec, UrbanAirship.Android.Core.nuspec, UrbanAirship.Android.FCM.nuspec, UrbanAirship.Android.GCM.nuspec, UrbanAirship.NETStandard.nuspec, UrbanAirship.Portable.nuspec, UrbanAirship.iOS.AppExtensions.nuspec, UrbanAirship.iOS.nuspec, airship.properties, samples/android/Sample.csproj, samples/android/packages.config, src/AirshipBindings.Android.ADM/AirshipBindings.Android.ADM.csproj, src/AirshipBindings.Android.ADM/packages.config, src/AirshipBindings.Android.Core/AirshipBindings.Android.Core.csproj, src/AirshipBindings.Android.Core/Transforms/Metadata.xml, src/AirshipBindings.Android.Core/packages.config, src/AirshipBindings.Android.FCM/AirshipBindings.Android.FCM.csproj, src/AirshipBindings.Android.FCM/packages.config, src/AirshipBindings.Android.GCM/AirshipBindings.Android.GCM.csproj, src/AirshipBindings.Android.GCM/packages.config, src/AirshipBindings.iOS/ApiDefinition.cs, src/AirshipBindings.iOS/StructsAndEnums.cs, src/SharedAssemblyInfo.cs
Updates iOS bindings to 9.4.0 and Android bindings to 9.5.2, and updates the various Xamarin support packages to the latest available.
We want to get customers on the latest 9.x so that they can have the relevant bugfixes and stuff before we manage to roll out support for SDK 10.
Built and ran the samples, verified that nothing was crashy or weird.
Xamboni continues to thrive, despite everything
=> MOBILE-311 Update iOS and Android SDKs to latest 9.x

CHANGELOG.md, Cartfile, UrbanAirship.Android.ADM.nuspec, UrbanAirship.Android.Core.nuspec, UrbanAirship.Android.FCM.nuspec, UrbanAirship.Android.GCM.nuspec, UrbanAirship.NETStandard.nuspec, UrbanAirship.Portable.nuspec, UrbanAirship.iOS.AppExtensions.nuspec, UrbanAirship.iOS.nuspec, airship.properties, samples/android/Sample.csproj, src/AirshipBindings.Android.ADM/AirshipBindings.Android.ADM.csproj, src/AirshipBindings.Android.Core/AirshipBindings.Android.Core.csproj, src/AirshipBindings.Android.FCM/AirshipBindings.Android.FCM.csproj, src/AirshipBindings.Android.GCM/AirshipBindings.Android.GCM.csproj, src/SharedAssemblyInfo.cs
Updates the iOS and Android SDKs to their latest patch.
There were some nasty bugs we patched recently, so this will spare our Xamarin users some difficulty.
I also updated the UrbanAirship.Core/FCM packages as well as the sample to build using the latest mono android (9.0) instead of pegging things to 8.1. I believe the mixture of 8.1 and 9.0 artifacts was causing some silent deployment errors resulting in Firebase woes, and we should probably be reflexively targeting the latest SDK version anyway.
Manually testing the sample app for iOS and Android.
=> [MOBILE-376] update iOS and Android SDKs to 10.0.3, 9.5.4

CHANGELOG.md, UrbanAirship.Android.ADM.nuspec, UrbanAirship.Android.Core.nuspec, UrbanAirship.Android.FCM.nuspec, UrbanAirship.Android.GCM.nuspec, UrbanAirship.NETStandard.nuspec, UrbanAirship.Portable.nuspec, airship.properties, src/AirshipBindings.Android.ADM/AirshipBindings.Android.ADM.csproj, src/AirshipBindings.Android.Core/AirshipBindings.Android.Core.csproj, src/AirshipBindings.Android.FCM/AirshipBindings.Android.FCM.csproj, src/AirshipBindings.Android.GCM/AirshipBindings.Android.GCM.csproj, src/SharedAssemblyInfo.cs
Updates Android SDK to 9.5.5
9.5.5 fixes a fairly critical bug, so we want to make sure our framework users are covered.
Manual testing of the sample app. Nothing has changed beyond the version of the incorporated aar, and the android update itself is quite small.
=> [android-9.5.5-patch] update android SDK to 9.5.5

CHANGELOG.md, UrbanAirship.Android.ADM.nuspec, UrbanAirship.Android.Core.nuspec, UrbanAirship.Android.FCM.nuspec, UrbanAirship.Android.GCM.nuspec, UrbanAirship.NETStandard.nuspec, UrbanAirship.Portable.nuspec, airship.properties, src/AirshipBindings.Android.ADM/AirshipBindings.Android.ADM.csproj, src/AirshipBindings.Android.Core/AirshipBindings.Android.Core.csproj, src/AirshipBindings.Android.FCM/AirshipBindings.Android.FCM.csproj, src/AirshipBindings.Android.GCM/AirshipBindings.Android.GCM.csproj, src/SharedAssemblyInfo.cs
One of the many plugin releases today in the aftermath of https://github.com/urbanairship/android-library-dev/pull/521, which necessitated an android version bump. For more context, see
urbanairship/android-library#115
urbanairship/android-library#114
=> [release-9.4.0] update android sdk references to 9.7.1

CHANGELOG.md, Cartfile, GettingStarted.md, UrbanAirship.NETStandard.nuspec, UrbanAirship.Portable.nuspec, UrbanAirship.iOS.AppExtensions.nuspec, UrbanAirship.iOS.LocationKit.nuspec, UrbanAirship.iOS.nuspec, airship.properties, src/SharedAssemblyInfo.CrossPlatform.cs, src/SharedAssemblyInfo.iOS.cs
Update the iOS SDK to 11.1 and fix an [issue](https://github.com/urbanairship/urbanairship-xamarin/issues/116) with the LocationKit nuget package.
- Customers couldn't install the LocationKit nuget package.
- Keep frameworks updated with the latest SDKs.
Local builds. Also created a local nuget repo and successfully installed the LocationKit NuGet package.
=> iOS Release 11.1 & NuGet Package fix

Cartfile, UrbanAirship.NETStandard.nuspec, UrbanAirship.Portable.nuspec, UrbanAirship.iOS.AppExtensions.nuspec, UrbanAirship.iOS.LocationKit.nuspec, UrbanAirship.iOS.nuspec, airship.properties, src/AirshipBindings.iOS/ApiDefinitions.cs, src/AirshipBindings.iOS/StructsAndEnums.cs, src/SharedAssemblyInfo.iOS.cs
This update Xamarin to use iOS SDK 12.1.2, and bumps the iOS nuspecs to 12.1.0. Everything else remains as is.
The changes in the bindings diff are mostly harmless, and much of it is just whitespace/line noise as a result of minor changes to the sourcekitten output for method prototypes. The meaningful stuff is in the attribute mutations.
I tested by running the sample app and verifying that nothing is wonky.
=> MOBILE-1119 Update Xamarin iOS to bind to SDK 12.1.2

src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/Analytics/CustomEvent.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs, src/AirshipBindings.Portable/AirshipBindings.Portable.Abstractions/Analytics/CustomEvent.cs, src/AirshipBindings.Portable/AirshipBindings.Portable.iOS/Airship.cs
We recenetly got a report that trying to add a custom event with properties causes crashes on iOS, when using the .NETStandard/Portable interface.
I think this has actually been a bug in .NETStandard/Portable for a while. The CustomEvent.Property<T> abstraction doesn't have properties defined for "stringValue", "boolValue", etc, but just a single value property that varies with the generic type. My best guess is that the compiler prevented us from catching it, due to the use of a "dynamic" keyword in the foreach loop. This effectively turns off static type checking, and defers issues with e.g. non-existent method calls to runtime.
This PR modifies those code paths to remove the use of "dynamic", perform explicit casting (checked by the compiler), and use the correct property.
Update:
Once …
=> [MOBLE-1296] fix custom event properties in netstandard/portable libs

UrbanAirship.NETStandard.nuspec, UrbanAirship.Portable.nuspec, UrbanAirship.iOS.nuspec, build.gradle, src/AirshipBindings.iOS.Automation/ApiDefinitions.cs, src/AirshipBindings.iOS.Core/ApiDefinitions.cs, src/AirshipBindings.iOS.Core/StructsAndEnums.cs
There were a few constants that were causing linker errors when building against the nupkg distribution. This doesn't seem to apply when testing using the "library project" sample, so we need to be more careful about testing using real packages in the future.
Nearly all of these are constants whose implementations have been removed from the SDK but for whatever reason didn't get removed from the headers. Two of them, namely UANotificationOptionNone and UAInAppMessageDisplayCoordinatorIsReadyKey are still in the SDK, but have inline definitions in the header file. We should probably also break the habit of doing this in the SDK, and Xamarin to my knowledge doesn't support binding them. I removed the latter for now, which is almost certainly something nobody will miss.
While I was testing I …
=> MOBILE-1303

samples/ios-unified/AirshipConfig.plist, samples/ios-unified/AppDelegate.cs, samples/ios-unified/SampleContentExtension/Entitlements.plist, samples/ios-unified/SampleContentExtension/Info.plist, samples/ios-unified/SampleContentExtension/MainInterface.storyboard, samples/ios-unified/SampleContentExtension/NotificationViewController.cs, samples/ios-unified/SampleContentExtension/NotificationViewController.designer.cs, samples/ios-unified/SampleContentExtension/SampleContentExtension.csproj, samples/ios-unified/SampleContentExtension/SampleContentExtension.sln, samples/ios-unified/iOSSample.sln
Adds content extension to xamarin
To clearly demonstrate how to use content extensions on the xamarin platform and to reach sample feature parity with our other platforms
Manually tested default content extension UI with push
=> [MOBILE-1310] add content extension to xamarin

.github/workflows/release.yaml, CHANGELOG.md, build.gradle, docs/build.gradle
Cleaned up changelog as well. Going forward we describe our releases in terms of the PCL/NetStandard and only tag those, bumping binding versions is a byproduct of that. To trigger a release, push the version of the netstandard library. This next release I assuming it will be `13.0.0`
=> [MOBILE-1387] Move release to github actions

UrbanAirship.Android.Core.nuspec, UrbanAirship.Android.Preference.nuspec, src/AirshipBindings.Android.FCM/packages.config, src/AirshipBindings.Android.Preference/packages.config, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/AirshipBindings.NETStandard.Abstractions.csproj, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/Attributes/AttributeEditor.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/IAirship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard/Airship.cs, src/AirshipBindings.Portable/AirshipBindings.Portable.Abstractions/AirshipBindings.Portable.Abstractions.csproj, src/AirshipBindings.Portable/AirshipBindings.Portable.Abstractions/Attributes/AttributeEditor.cs, src/AirshipBindings.Portable/AirshipBindings.Portable.Abstractions/IAirship.cs, src/AirshipBindings.Portable/AirshipBindings.Portable.Android/Airship.cs, src/AirshipBindings.Portable/AirshipBindings.Portable.iOS/Airship.cs, src/AirshipBindings.Portable/AirshipBindings.Portable/Airship.cs, src/AirshipBindings.iOS.Core/ApiDefinitions.cs
This adds attribute support to the .NETStandard and Portable libraries. The pattern is similar to the way we ended up implementing CustomEvent properties recently, with generics and exhaustive type checking instead of Object casts, which are illegal in C# in situations that would seem reasonable for Java. Luckily C# has enough syntactic sugar to make it reasonably painless.
On iOS and Android I was able to set attributes from an ad-hoc test app, using locally built nuget packages, and verify they were being bridged properly to the SDK.
Note: VS will complain about missing references and ask you to install a variety of androidx packages by hand unless you change the target SDK version of the forms app to API 29.
=> [MOBILE-1222] .NETStandard/portable attribute support

src/AirshipBindings.Android.ADM/AirshipBindings.Android.ADM.csproj, src/AirshipBindings.Android.Core/AirshipBindings.Android.Core.csproj, src/AirshipBindings.Android.FCM/AirshipBindings.Android.FCM.csproj, src/AirshipBindings.Android.Preference/AirshipBindings.Android.Preference.csproj
This is a very minor change, but we should be compiling our bindings with the latest target framework settings, since that's what we're doing for the urbanairship modules they wrap.
=> [update-target-framework-versions] update android target framework settings to 10.0

src/AirshipBindings.iOS.Core/Additions/UAirship.cs, src/AirshipBindings.iOS.Core/AirshipBindings.iOS.Core.csproj
Add plugin tracking for iOS to Xamarin component. Now Xamarin iOS apps will report something like `"X-UA-Frameworks" = "xamarin:13.1.1.0";` to analytics when they run.
Better understanding of the usage of our Xamarin components.
Ran on device with trace-level logging to see headers uploaded to Analytics.
The `registerSDKExtension:version:` method and `UASDKExtension` enum are not exposed through our API bindings. They are labelled `:nodoc:` in the iOS SDK and Xamboni ignores `:nodoc:` items, assuming they are SDK-private. I temporarily exposed the two and ran Xamboni to generate the appropriate bindings, which I then copied into `UAirship.cs`, my class that actually registers the sdk extension. It's kinda ugly, but works just fine. If we choose to expose the method and enum in the future, …
=> [MOBILE-1142] Add plugin tracking for iOS

src/AirshipBindings.Android.Core/Additions/UAirship.cs
Adds plugin tracking to android
Was able to get it to break on the correct call on sample launch:
=> [MOBILE-1392] add plugin tracking for android

UrbanAirship.Android.ADM.nuspec, UrbanAirship.Android.Accengage.nuspec, UrbanAirship.Android.Core.nuspec, UrbanAirship.Android.FCM.nuspec, UrbanAirship.Android.Preference.nuspec, UrbanAirship.NETStandard.nuspec, UrbanAirship.Portable.nuspec, UrbanAirship.iOS.Accengage.nuspec, UrbanAirship.iOS.Automation.nuspec, UrbanAirship.iOS.Core.nuspec, UrbanAirship.iOS.ExtendedActions.nuspec, UrbanAirship.iOS.Location.nuspec, UrbanAirship.iOS.MessageCenter.nuspec, UrbanAirship.iOS.NotificationContentExtension.nuspec, UrbanAirship.iOS.NotificationServiceExtension.nuspec, UrbanAirship.iOS.nuspec
There were a variety of warnings when running the packaging script, such as:
Attempting to build package from 'UrbanAirship.Android.Core.nuspec'.
Successfully created package '/Users/brian.batchelder/source/mobile-1142-urbanairship-xamarin-Xamarin-add-plugin-tracking-on-iOS/build/urbanairship.android.core.12.2.0.nupkg'.
WARNING: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
- Add lib or ref assemblies for the monoandroid target framework
WARNING: NU5130: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder have compatible matches, but not exact matches in the other location. Unless intentional, consult the …
=> [fix-target-framework-dependencies] fix target framework dependencies

src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/AirshipBindings.NETStandard.Abstractions.csproj, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/Message Center/MessagePage.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/AirshipBindings.NETStandard.Android.csproj, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/MessagePageRenderer.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/Properties/AssemblyInfo.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/Resources/Resource.designer.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/packages.config, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/AirshipBindings.NETStandard.iOS.csproj, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/AirshipForms.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/MessagePageRenderer.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Properties/AssemblyInfo.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/packages.config, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard/AirshipBindings.NETStandard.csproj
This PR adds a Forms control deriving from `ContentPage` that allows easy loading of message center messages in a cross platform app. ContentPages in Forms are analogous to view controllers, and literally descend from `UIViewController` on iOS.
One of the consequences of this is that our NETStandard library will now have an explicit dependency on Xamarin.Forms for the first time. We also don't currently have NETStandard bindings for anything message center related, such as fetching and access to the message list, so that will need to be done in another ticket if this is going to be useful to anyone.
Here's an example of how to use it
```               
var messagePage = new MessagePage();
// Load the message
messagePage.MessageId = "SOME_MESSAGE_ID";
// Sign up for events …
```
=> [MOBILE-1486] MessagePage

src/AirshipBindings.NETStandard/AirshipBindings.NETStandard/Airship.cs
The definition was missing [here](https://github.com/urbanairship/urbanairship-xamarin/pull/142).
(my bad 😭)
and thanks to @rlepinski for noticing.
=> Add the deep link event listener definition

src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/IAirship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard/Airship.cs
What do these changes do?
This PR adds data collection properties (data collection and push token registration) to the NetStandard lib.
Why are these changes necessary?
To support data collection feature on Xamarin.
How did you verify these changes?
Via sample app.
=> [MOBILE-1559] Add data collection properties

src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/IAirship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard/Airship.cs
Adds a method to edit named user attributes
To keep the xamarin plugin up to date with the native features
In the logs
```
2020-06-10 12:28:28.162 7637-7675/com.urbanairship.sample V/Xamarin Sample - UALib: PreferenceDataStore - Saving preference: com.urbanairship.nameduser.ATTRIBUTE_MUTATION_STORE_KEY value: [[{"timestamp":"2020-06-10T16:27:35","value":"Rico","key":"nickname","action":"set"}],[{"timestamp":"2020-06-10T16:28:28","value":"Rico","key":"nickname","action":"set"}]]
2020-06-10 12:28:28.166 7637-7637/com.urbanairship.sample V/Xamarin Sample - UALib: AirshipService - Received intent: Intent { act=RUN_JOB cmp=com.urbanairship.sample/com.urbanairship.job.AirshipService (has extras) }
2020-06-10 12:28:28.167 7637-7703/com.urbanairship.sample V/Xamarin Sample - UALib: AirshipService …
```
=> [MOBILE-1561] Add EditNamedUserAttributes method

SampleApp/SampleApp.iOS/AppDelegate.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/IAirship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard/Airship.cs
We've been slowly moving towards a style of events/delegates that uses `EventHandler<T>` instead of custom delegate types. This brings the deep link events up to date, and also fixes a few issues with the iOS part of the Sample app that I'll call out in the diff.
=> [MOBILE-1722] standardize event handlers, fix iOS sample crash

SampleApp/SampleApp.Android/Resources/drawable/inbox.xml, SampleApp/SampleApp.Android/SampleApp.Android.csproj, SampleApp/SampleApp/AppResources.Designer.cs, SampleApp/SampleApp/AppResources.resx, SampleApp/SampleApp/MessageCenterViewController.xaml, SampleApp/SampleApp/MessageCenterViewController.xaml.cs, SampleApp/SampleApp/TabbedPageView.xaml
Add message center screen to Xamarin sample.
To test MessageCenter functionality.
Using the sample App.
**iOS**
**Android**
The **IsRead** attribute is missing now, I added a commented code related to the indicator of isRead message, we can use it once this one is ready.
=> [Mobile-1706] - Add message center screen to Xamarin sample

README.md, SampleApp/README.md, SampleApp/SampleApp.Android/build.gradle, SampleApp/SampleApp.iOS/build.gradle, SampleApp/build.gradle, docs/mainpage.md
Some of the documentation got out-of-date when the new SampleApp was created. This PR fixes the documentation and simplifies and corrects the SampleApp build.
Some complaints on GitHub.
Local builds in clean repos.
It is now possible to build the Sample App, and it builds both iOS and Android flavors using `./gradlew :SampleApp:build`.
=> [MOBILE-1670] Update docs and new sample app to make them consistent.

src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard/Airship.cs
These changes add methods "MarkAsRead" and "DeleteMessage" to Xamarin NETStandard
Because customers need this
By adding a button "mark as read" and "delete" in the sample app, and checking that it's working well.
=> [MOBILE-1890] Add a way to mark message center messages read and deleted

src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs
I noticed this when working on something else. VS was warning about OnChannelUpdate being unused, and it turned out that we were calling the OnChannelCreation event for both creation and updates. This fixes it.
=> fix OnChannelUpdate event

src/AirshipBindings.iOS.common/build.gradle, wcarthage
This is a temporary workaround for https://github.com/Carthage/Carthage/issues/3019. Carthage is incompatable with XCode 12 at the moment due to the presence of arm64 simulator slices. This script wraps the carthage command to exclude that architecture.
=> [carthage-wrapper] wcarthage

.gitignore, .gitmodules, README.md, requirements.txt, src/ios-common-build.gradle
This installs xamboni through pip instead of a git submodule. Since xamboni is private for now we can just point pip to the github repo, with `@foo` suffixes after `.git` to specify branches or specific commits if necessary. `requirements.txt` is the typical way to lock dependencies in this ecosystem. Aside from the new installation mechanism the only real change here is that the location of the xamboni directory has moved to `src`.
=> [MOBILE-1748] install xamboni through pip

SampleApp/SampleApp.iOS/SampleApp.iOS.csproj, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs, src/AirshipBindings.iOS.Automation/AirshipAutomation.cs, src/AirshipBindings.iOS.Automation/AirshipBindings.iOS.Automation.csproj, src/AirshipBindings.iOS.Core/AirshipBindings.iOS.Core.csproj, src/AirshipBindings.iOS.Core/AirshipCore.cs, src/AirshipBindings.iOS.ExtendedActions/AirshipBindings.iOS.ExtendedActions.csproj, src/AirshipBindings.iOS.ExtendedActions/AirshipExtendedActions.cs, src/AirshipBindings.iOS.Location/AirshipBindings.iOS.Location.csproj, src/AirshipBindings.iOS.Location/AirshipLocation.cs, src/AirshipBindings.iOS.MessageCenter/AirshipBindings.iOS.MessageCenter.csproj, src/AirshipBindings.iOS.MessageCenter/AirshipMessageCenter.cs, src/AirshipBindings.iOS.common/build.gradle, wcarthage
We've had a few reports that IAA doesn't work in Xamarin, and it turns out that the module is being stripped out when it's not referenced in code. I've tried various things from linker settings to Preserve annotations, but the one thing that seems to work is adding a dummy  static "Init" method that can be called to force the compiler to include the module. This is a potential problem for any module aside from AirshpCore, which you already have to reference in order to call takeOff.
Since the NETStandard library only directly references Core and Message Center, I modified it to initialize Automation and Extended Actions, so that NETStandard users don't have to bother about this. Native apps will need to call the appropriate init methods for the modules they're using, which will need clear …
=> [MOBILE-1887] iOS module init

SampleApp/SampleApp/App.xaml.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Abstractions/IAirship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.Android/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard/Airship.cs, wcarthage
Add a message center display listener. If set, displayMessageCenter and displayMessage route to the built in message center. If not, the default message center is displayed.
Allow for the custom Xamarin Forms MC to be used instead of the OOTB one.
Ran sample apps and verified that the behavior is as expected.
=> [MOBILE-1932] Add Xamarin forms message center listener

.github/workflows/release.yaml
Updates to the new modular GCP setup action.
So that deploys continue working.
Doing it live, but tested the new action in a private repo and it installed the GCP CLI utils without issue.
=> [MOBILE-2438] Update setup-cloud action in release workflow

CHANGELOG.md, SampleApp/SampleApp.iOS/SampleApp.iOS.csproj, SampleApp/SampleApp.iOS/SampleContentExtension/SampleContentExtension.csproj, SampleApp/SampleApp.iOS/SampleContentExtension/packages.config, SampleApp/SampleApp.iOS/SampleServiceExtension/SampleServiceExtension.csproj, SampleApp/SampleApp.iOS/SampleServiceExtension/packages.config, SampleApp/SampleApp/SampleApp.csproj, UrbanAirship.NETStandard.nuspec, UrbanAirship.iOS.Accengage.nuspec, UrbanAirship.iOS.Automation.nuspec, UrbanAirship.iOS.Basement.nuspec, UrbanAirship.iOS.Chat.nuspec, UrbanAirship.iOS.Core.nuspec, UrbanAirship.iOS.ExtendedActions.nuspec, UrbanAirship.iOS.Location.nuspec, UrbanAirship.iOS.MessageCenter.nuspec, UrbanAirship.iOS.NotificationContentExtension.nuspec, UrbanAirship.iOS.NotificationServiceExtension.nuspec, UrbanAirship.iOS.PreferenceCenter.nuspec, UrbanAirship.iOS.nuspec, airship.properties, build.gradle, src/SharedAssemblyInfo.Common.cs, src/SharedAssemblyInfo.CrossPlatform.cs, src/SharedAssemblyInfo.iOS.cs
Release SDK 15.0.3
Contain the reduce nuget package path issue
I added a new value to the airship.properties file called **iosNugetVersion** to differentiate the nuget version from the iOS sdk version. I will create a ticket for Android since it's not a priority now and we need to release this version as soon as possible.
=> Release SDK 15.0.3

.github/workflows/release.yaml
Switches back to using `gsutil` for doc uploads, because the fancy action doesn't give as much control over the upload path and file name.
The doc bundle for the last release ended up at the wrong path.
=> [MOBILE-3542] Fix doc upload path in release workflow

.github/workflows/release.yaml
Fixing up the release workflow, which is failing on the doc upload step.
=> Add setup-gcloud to release workflow, to fix doc uploads

SampleApp/SampleApp.iOS/AppDelegate.cs, src/AirshipBindings.NETStandard/AirshipBindings.NETStandard.iOS/Airship.cs, src/AirshipBindings.iOS.Core/StructsAndEnums.cs
- Uncomments the line that adds custom event properties to the native custom event object
- Deprecates `UALogLevel.Trace` and adds `UALogLevel.Verbose` (with the same value, so they'll do the same thing, but `Trace` will show a warning in the IDE)
Customer reported custom events were missing properties on iOS, and we changed the LogLevel in SDK 17, but missed the rename in this repo.
* Reproduced the customer's issue using RTDS to view the payloads
* Wired up a custom event to a button on the sample app home screen and verified that the correct payloads with properties were showing up in the RTDS stream
* Migrated our single usage of `Trace` to `Verbose` and ran the sample app
=> [MOBILE-4082] Fix missing custom event properties and log level trace->verbose on iOS
